-- AlterTable
ALTER TABLE "Shift" ADD COLUMN     "clockInLat" DOUBLE PRECISION,
ADD COLUMN     "clockInLon" DOUBLE PRECISION,
ADD COLUMN     "clockOutLat" DOUBLE PRECISION,
ADD COLUMN     "clockOutLon" DOUBLE PRECISION;
